/*
 * Danish Data Portal - HPC API
 *
 * A Web API for HPC centers to communicate with the Danish Data Portal to manage access and data transfers
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type HPCMessageTypeEnum string

// List of HPCMessageTypeEnum
const (
	CREATE_PROJECT HPCMessageTypeEnum = "CreateProject"
	DELETE_PROJECT HPCMessageTypeEnum = "DeleteProject"
	CREATE_PROJECT_ACCESS HPCMessageTypeEnum = "CreateProjectAccess"
	DELETE_PROJECT_ACCESS HPCMessageTypeEnum = "DeleteProjectAccess"
	DISABLE_PROJECT_ACCESS HPCMessageTypeEnum = "DisableProjectAccess"
	ENABLE_PROJECT_ACCESS HPCMessageTypeEnum = "EnableProjectAccess"
	RESET_PASSWORD HPCMessageTypeEnum = "ResetPassword"
	DATA_DELIVERY_READY HPCMessageTypeEnum = "DataDeliveryReady"
	DELETE_DATA_FILE HPCMessageTypeEnum = "DeleteDataFile"
	RETURN_DATA_FILE HPCMessageTypeEnum = "ReturnDataFile"
)
