/*
 * Danish Data Portal - HPC API
 *
 * A Web API for HPC centers to communicate with the Danish Data Portal to manage access and data transfers
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type MessageDto struct {

	MessageId string `json:"messageId,omitempty"`

	MessageType *HPCMessageTypeEnum `json:"messageType,omitempty"`

	Timestamp time.Time `json:"timestamp,omitempty"`

	Data string `json:"data,omitempty"`
}
