/*
 * Danish Data Portal - HPC API
 *
 * A Web API for HPC centers to communicate with the Danish Data Portal to manage access and data transfers
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserAccessCreatedDto struct {

	AccessIdentifier string `json:"accessIdentifier,omitempty"`

	LoginName string `json:"loginName,omitempty"`

	OneTimePassword string `json:"oneTimePassword,omitempty"`
}
